name: gmana_flutter

packages:
  - apps/**
  - libs/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: dart analyze .
  format:
    exec: dart format . --set-exit-if-changed
  outdated:
    exec: flutter pub outdated
  test:
    exec: flutter test
  lint:
    exec: dart run custom_lint