name: gmana_wallet
description: Personal finance experts to help you manage your finances.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  currency_picker: ^2.0.14
  cupertino_icons: ^1.0.5
  hooks_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  go_router: ^6.0.1
  supabase_flutter: ^1.3.1
  google_fonts: ^4.0.1
  cached_network_image: ^3.2.3
  intl: ^0.17.0
  image_picker: ^0.8.6+1
  shared_preferences: ^2.0.17
  connectivity_plus: ^3.0.2
  flutter_spinkit: ^5.1.0
  fpdart: ^0.4.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  gmana:
    path: ../../libs/gmana
  gmana_ext:
    path: ../../libs/gmana_ext
  flutter_svg: ^1.1.6
  logger: ^1.1.0
  flutter_native_splash: ^2.2.16
  font_awesome_flutter: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  mockito: ^5.3.2
  riverpod_generator: ^1.1.1
  flutter_launcher_icons: ^0.11.0
  go_router_builder: ^1.0.16
  injectable_generator: ^2.1.3
  material_color_utilities: ^0.2.0
  gmana_lints:
    path: ../../libs/gmana_lints

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/flags/
    - assets/icons/

flutter_icons:
  android: 'ic_launcher'
  ios: true
  image_path: 'assets/icons/icon.png'
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: 'assets/icons/icon.png'
    background_color: '#fff'
    theme_color: '#fff'
  windows:
    generate: true
    image_path: 'assets/icons/icon.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/icons/icon.png'

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/icons/W400.png'
  color_dark: '#1f2937'
  image_dark: 'assets/icons/W400.png'
  android: true
  ios: true
  # android_gravity: fill
  # ios_content_mode: scaleAspectFill
