import 'five_digit.dart';
import 'four_digit.dart';
import 'six_digit.dart';
import 'three_digit.dart';

Map<String, RegExp> postalCodePatterns = {
  'AD': RegExp(r'^AD\d{3}$'),
  'AT': fourDigit,
  'AU': fourDigit,
  'BE': fourDigit,
  'BG': fourDigit,
  'CA': RegExp(
      r'^[ABCEGHJKLMNPRSTVXY]\d[ABCEGHJ-NPRSTV-Z][\s\-]?\d[ABCEGHJ-NPRSTV-Z]\d$',
      caseSensitive: false),
  'CH': fourDigit,
  'CZ': RegExp(r'^\d{3}\s?\d{2}$'),
  'DE': fiveDigit,
  'DK': fourDigit,
  'DZ': fiveDigit,
  'EE': fiveDigit,
  'ES': fiveDigit,
  'FI': fiveDigit,
  'FR': RegExp(r'^\d{2}\s?\d{3}$'),
  'GB': RegExp(r'^(gir\s?0aa|[a-z]{1,2}\d[\da-z]?\s?(\d[a-z]{2})?)$',
      caseSensitive: false),
  'GR': RegExp(r'^\d{3}\s?\d{2}$'),
  'HR': RegExp(r'^([1-5]\d{4}$)'),
  'HU': fourDigit,
  'ID': fiveDigit,
  'IL': fiveDigit,
  'IN': sixDigit,
  'IS': threeDigit,
  'IT': fiveDigit,
  'JP': RegExp(r'^\d{3}\-\d{4}$'),
  'KE': fiveDigit,
  'KM': fiveDigit,
  'LI': RegExp(r'^(948[5-9]|949[0-7])$'),
  'LT': RegExp(r'^LT\-\d{5}$'),
  'LU': fourDigit,
  'LV': RegExp(r'^LV\-\d{4}$'),
  'MX': fiveDigit,
  'NL': RegExp(r'^\d{4}\s?[a-z]{2}$', caseSensitive: false),
  'NO': fourDigit,
  'PL': RegExp(r'^\d{2}\-\d{3}$'),
  'PT': RegExp(r'^\d{4}\-\d{3}?$'),
  'RO': sixDigit,
  'RU': sixDigit,
  'SA': fiveDigit,
  'SE': RegExp(r'^\d{3}\s?\d{2}$'),
  'SI': fourDigit,
  'SK': RegExp(r'^\d{3}\s?\d{2}$'),
  'TN': fourDigit,
  'TW': RegExp(r'^\d{3}(\d{2})?$'),
  'UA': fiveDigit,
  'US': RegExp(r'^\d{5}(-\d{4})?$'),
  'ZA': fourDigit,
  'ZM': fiveDigit
};
